avcenc: remove extra arguments on calling local function
Warning introduced in the initial commit.

avcenc.c:1844:41: warning: too many arguments in call to 'end_picture'
    end_picture(slice_type, next_is_bpic);
    ~~~~~~~~~~~                         ^

Signed-off-by: Victor Toso <victortoso@redhat.com>