Fix compilation failures
When wayland-client meets the requirement but libva-wayland doesn't
exist, we will get the following error because USE_WAYLAND and
HAVE_VA_WAYLAND don't keep consistency

  CXXLD    mpeg2vldemo
../common/.libs/libva-display.a(libva_display_la-va_display.o):(.data.rel+0x0):
undefined reference to `va_display_hooks_wayland'
collect2: error: ld returned 1 exit status

This fixes https://github.com/01org/libva-utils/issues/42

Signed-off-by: Xiang, Haihao <haihao.xiang@intel.com>