test/fixture: fix GCC 10.0.1 error with drmDevicePaths
drmDevicePaths is static/constant and only used in one
method (getDisplay).  Thus, it is unnecessary to declare
it as a member variable.  Instead, just declare and
initialize in getDisplay and use proper C++ semantics.

This also fixes a GCC 10.0.1 error due to improper
C++11 constructor list-initialization syntax:

  error: list-initialize for non-class type must not
         be parenthesized.

Fixes #191

Signed-off-by: U. Artie Eoff <ullysses.a.eoff@intel.com>