sfcsample: drop unused Linux-only header
VDecAccelVA.cpp:35:10: fatal error: 'linux/fb.h' file not found
 #include <linux/fb.h>
          ^~~~~~~~~~~~